"""Add role to memeber

Revision ID: 19316f07bc9b
Revises: a2d5453e6a58
Create Date: 2026-04-13 02:13:51.281738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19316f07bc9b'
down_revision: Union[str, Sequence[str], None] = 'a2d5453e6a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('role', sa.Enum('user', 'admin', name='memberrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'role')
    # ### end Alembic commands ###
