"""fix date columns timezone

Revision ID: 7e51810ce786
Revises: d8b2114a1c79
Create Date: 2026-09-03 18:02:46.590486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e51810ce786'
down_revision: Union[str, Sequence[str], None] = 'd8b2114a1c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('projects', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('works', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('works', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'end_date',
               existing_type=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('works', 'start_date',
               existing_type=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('projects', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
