"""add_last_read_message_id_to_chat_room_member

Revision ID: a930eb13180a
Revises: 7e51810ce786
Create Date: 2026-09-04 22:11:01.816890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a930eb13180a'
down_revision: Union[str, Sequence[str], None] = '7e51810ce786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room_members', sa.Column('last_read_message_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('chat_room_members_last_read_message_id_fkey', 'chat_room_members', 'chat_messages', ['last_read_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_room_members_last_read_message_id_fkey', 'chat_room_members', type_='foreignkey')
    op.drop_column('chat_room_members', 'last_read_message_id')
    # ### end Alembic commands ###
