"""update member field

Revision ID: a97f8719f6f8
Revises: 19316f07bc9b
Create Date: 2026-04-19 16:37:03.279205

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97f8719f6f8'
down_revision: Union[str, Sequence[str], None] = '19316f07bc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('members', 'gender')
    op.drop_column('members', 'nickname')
    op.drop_column('members', 'phone_num')
    op.drop_column('members', 'dept')
    op.drop_column('members', 'birth')
    op.drop_column('members', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('birth', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('dept', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('phone_num', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('gender', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('members', 'username')
    # ### end Alembic commands ###
