"""Add projectmember

Revision ID: f1c30c5374e8
Revises: a97f8719f6f8
Create Date: 2026-04-20 18:34:51.396235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c30c5374e8'
down_revision: Union[str, Sequence[str], None] = 'a97f8719f6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


providertype_enum = sa.Enum('local', 'google', 'kakao', 'naver', name='providertype')
workstate_enum = sa.Enum('planned', 'doing', 'done', name='workstate')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    providertype_enum.create(op.get_bind(), checkfirst=True)
    workstate_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'member_id')
    )
    op.alter_column('members', 'provider',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('local', 'google', 'kakao', 'naver', name='providertype'),
               existing_nullable=False,
               postgresql_using='provider::providertype')
    op.drop_constraint(op.f('members_hashed_password_key'), 'members', type_='unique')
    op.create_foreign_key(None, 'projects', 'members', ['leader_id'], ['id'])
    op.drop_column('projects', 'img_url')
    op.add_column('works', sa.Column('author_id', sa.Uuid(), nullable=False))
    op.alter_column('works', 'state',
               existing_type=sa.SMALLINT(),
               type_=sa.Enum('planned', 'doing', 'done', name='workstate'),
               existing_nullable=False,
                postgresql_using="""
                        CASE state
                            WHEN 0 THEN 'planned'
                            WHEN 1 THEN 'doing'
                            WHEN 2 THEN 'done'
                        END::workstate
                        """
                )
    op.create_foreign_key(None, 'works', 'members', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.alter_column('works', 'state',
               existing_type=sa.Enum('planned', 'doing', 'done', name='workstate'),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.drop_column('works', 'author_id')
    op.add_column('projects', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_unique_constraint(op.f('members_hashed_password_key'), 'members', ['hashed_password'], postgresql_nulls_not_distinct=False)
    op.alter_column('members', 'provider',
               existing_type=sa.Enum('local', 'google', 'kakao', 'naver', name='providertype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('project_members')
    # ### end Alembic commands ###
