"""remove works useless field

Revision ID: f2f80280bd35
Revises: f1c30c5374e8
Create Date: 2026-04-20 18:53:20.381374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f80280bd35'
down_revision: Union[str, Sequence[str], None] = 'f1c30c5374e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'priority')
    op.drop_column('works', 'memo')
    op.drop_column('works', 'remark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('remark', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('memo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('priority', sa.SMALLINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
